### ISSUE TITLE
Sorting by item id creates artificial sequential patterns

### ISSUE THREAD

**Issue by asash** [yueqirex/LRURec#1] opened 2023-10-20 08:21 UTC
Hi, thanks for the interesting paper and publishing the code. 

When I browsed your code, I found that you're sorting the data according to item ID when the timestamps are in a tie (this line: 
https://github.com/yueqirex/LRURec/blob/ac5e902ea1e28e6b07f73b0a04eb25ef0b2e1956/datasets/base.py#L99)

This is problematic because it creates artificial patterns in the data (in case of a tie, a higher item ID always follows a smaller item ID). This is specifically problematic for the datasets with a large number of ties, like ML-1M (in ML-1M, the proportion of non-unique timestamps is almost half). Therefore, the models' task becomes easier, and all metrics become inflated for sequential models. I made a similar mistake in the past, and in my experience, it increases metrics like NDCG by ~20%. 

As the same dataset is used for evaluating all models, the overall comparison remains fair; however, the results are not comparable with other papers which use the same datasets (e.g., many papers used the datasets from the SASRec repo https://github.com/kang205/SASRec/tree/master/data).

It would be great to add an option for another mechanism of tie-breaking (e.g. sort by the hash of (timestamp, user_id, item_id)) and run the experiments in a way that results are comparable with other papers.

**Comment by Yueeeeeeee** [comment] 2023-10-22 00:00
Hi, thanks for letting us know about it, in our experiments both baseline and LRU are evaluated under identical settings. For datasets other than ML-1M, we directly adopt the processed SASRec data (see data folder) and all user / item IDs can match exactly (you can verify this by checking out the **umap** and **smap** keys in the processed dataset.pkl file). We are currently experimenting with the ML-1M dataset from the original SASRec implementation, and will follow up if we find any difference in our results.

**Comment by AaronHeee** [comment] 2023-10-22 06:16
Hi @asash, thanks for sharing the concerns and thanks for the timely responses from @Yueeeeeeee. There are some additional points from our end:

1. We've noticed that sorted item IDs in user sequences may contain artificial sequential patterns. However, as far as we know, this only affects the performance of NLP-based recommender system models, where ID numbers themselves carry semantic information for prediction. In contrast, LRU4Rec and the baselines are purely ID-based models with randomly initialized ID embeddings, and thus may not be affected in the same way.

2. We appreciate your comment about "**sorted IDs** --(1)--> **specific leave-one-out data splitting** --(2)--> **easier tasks and higher performance**". While we understand the rationale behind (1), we are curious about why (2) holds true. In other words, how does such data splitting lead to better prediction performance? Are there noticeable patterns in the original item indexing? We would appreciate any additional insights you could provide.

3. To ensure the reliability of our experiments, as mentioned by @Yueeeeeeee, we have verified our datasets and data splitting in both the baseline and LRU4Rec experiments. Additionally, we have two more considerations, and your feedback is welcome:

    1. We introduce an alternative option for tie-breaking.
    2. Regarding ML-1M, where you mentioned "the proportion of non-unique timestamps is almost half," we recognize that changing the tie-breaking method alone may not completely resolve this issue. We have come to understand that the cause may be MovieLens dataset is not an ideal choice for sequential recommendation, as discussed in this [paper](https://ceur-ws.org/Vol-2955/paper8.pdf). Therefore, we will report our current results while adding footnotes in our camera-ready version to mention this concern about the MovieLens dataset.
 
Looking forward to hearing feedback from your side! Thanks!

**Comment by Yueeeeeeee** [comment] 2023-10-25 17:04
Hi, we have rerun the experiments on LRURec with the updated ML-1M implementation.  We will also update baseline results that have the same issue and reflect the new results in our updated manuscript. A short summerization of our LRURec results: NDCG@10: 0.19065, NDCG@20: 0.21767, Recall@10: 0.32402, Recall@20: 0.43118. Hope that clarifies your question:)

**Comment by asash** [comment] 2023-10-25 17:20
Hi, thanks for your comments and for running these updated experiments!
The result sounds interesting; I hope to find time to try it in my experiments soon.

**Comment by Yueeeeeeee** [comment] 2023-10-25 17:33
Sure, we will update the implementation in this repo accordingly. Closing the issue.

**Closed by Yueeeeeeee** 2023-10-25 17:33 UTC
